{{- if and (get .Values.conditionalPackageInstalls "argo-workflows") .Values.defaultBucketConfiguration.useLocalStack }}
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-artifact-s3-creds
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
stringData:
  accessKey: "test"
  secretKey: "test"
{{- end }}
---
{{- if and (eq .Values.cloudProvider "gcp") .Values.charts.argo-workflows.artifactRepository.gcs.serviceAccountKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.charts.argo-workflows.artifactRepository.gcs.serviceAccountKeySecret.name }}
type: Opaque
data:
  {{ .Values.charts.argo-workflows.artifactRepository.gcs.serviceAccountKeySecret.key }}: {{ .Values.gcs.bucketOperationServiceAccountKey | default "" | b64enc }}
{{- end }}
---
{{- if and (eq .Values.cloudProvider "azure") .Values.charts.argo-workflows.artifactRepository.azure.accountKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.charts.argo-workflows.artifactRepository.azure.accountKeySecret.name }}
type: Opaque
data:
  {{ .Values.charts.argo-workflows.artifactRepository.azure.accountKeySecret.key }}: {{ .Values.azure.storageAccountKey | default "" | b64enc }}
{{- end }}
