{{- if eq .Values.cloudProvider "gcp" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrations-default-gcs-config
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  GCS_REGION: {{ .Values.gcp.region }}
  GCS_ENDPOINT_URL: {{ .Values.gcsBucketConfiguration.endpoint }}
  GCS_BUCKET_NAME: {{ .Values.gcsBucketConfiguration.bucketName | default (printf "migrations-default-%s" .Release.Namespace) }}
{{- end }}
